//! Economic order intent — the durable, idempotent unit of authorisation.
//!
//! An intent is what the system makes durable *before* any venue submission
//! (R1.1). It is immutable: a replace is a new intent linked by trace, never a
//! mutation of an old one. The idempotency key is generated by us, so a retry
//! of the same decision collapses onto the same intent instead of creating a
//! second one (R1.2).
//!
//! Construction is the only way to build one and it validates, so an invalid
//! intent does not exist to be handled downstream.

use sentinel_types::{Authority, ClientOrderId, Instrument, OrderKind, Price, Qty, Side, TraceId};

use crate::error::IntentError;

/// An authorised piece of economic exposure, before anyone has been told.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EconomicOrderIntent {
    /// The idempotency key, and what the venue will know the order by.
    ///
    /// One field rather than the Python's two. They were always equal, and two
    /// names for one value is two chances to compare the wrong one.
    pub client_order_id: ClientOrderId,
    /// What is being traded.
    pub instrument: Instrument,
    /// Direction.
    pub side: Side,
    /// How much. Always positive.
    pub qty: Qty,
    /// How the venue should execute it.
    pub kind: OrderKind,
    /// The resting price, for a limit order.
    pub limit_price: Option<Price>,
    /// The trigger price, for a venue-native stop.
    pub stop_price: Option<Price>,
    /// Whose authority this is under (R1.13).
    pub authority: Authority,
    /// The causal chain this belongs to.
    pub trace_id: TraceId,
    /// The market quote observed at decision time.
    ///
    /// Stamped here rather than derived later, so that
    /// `fill price - quote_at_decision` is an honest slippage number: it
    /// measures everything between deciding and filling, including the parts
    /// that were our own fault.
    pub quote_at_decision: Option<Price>,
}

impl EconomicOrderIntent {
    /// Build and validate an intent.
    ///
    /// # Errors
    /// [`IntentError`] when the intent is not one this system will authorise:
    /// a non-positive quantity or price, a missing price the kind requires, an
    /// empty idempotency key, or a stop-limit — which is refused rather than
    /// approximated, because every venue resolves the two prices differently
    /// and an adapter guessing which one we meant is a guess about money.
    #[expect(
        clippy::too_many_arguments,
        reason = "an intent is a record of ten independent facts; grouping them \
                  into sub-structs to satisfy an arity count would put the \
                  validation further from the fields it validates"
    )]
    pub fn new(
        client_order_id: ClientOrderId,
        instrument: Instrument,
        side: Side,
        qty: Qty,
        kind: OrderKind,
        limit_price: Option<Price>,
        stop_price: Option<Price>,
        authority: Authority,
        trace_id: TraceId,
        quote_at_decision: Option<Price>,
    ) -> Result<Self, IntentError> {
        if client_order_id.is_empty() {
            return Err(IntentError::EmptyIdempotencyKey);
        }
        if !qty.is_positive() {
            return Err(IntentError::NonPositiveQty);
        }
        if limit_price.is_some_and(|p| !p.is_positive())
            || stop_price.is_some_and(|p| !p.is_positive())
            || quote_at_decision.is_some_and(|p| !p.is_positive())
        {
            return Err(IntentError::NonPositivePrice);
        }
        if limit_price.is_some() && stop_price.is_some() {
            return Err(IntentError::StopLimitUnsupported);
        }
        if kind.needs_limit_price() && limit_price.is_none() {
            return Err(IntentError::MissingPrice { kind });
        }
        if kind.needs_stop_price() && stop_price.is_none() {
            return Err(IntentError::MissingPrice { kind });
        }
        Ok(Self {
            client_order_id,
            instrument,
            side,
            qty,
            kind,
            limit_price,
            stop_price,
            authority,
            trace_id,
            quote_at_decision,
        })
    }

    /// A market order.
    ///
    /// # Errors
    /// [`IntentError`] under the same rules as [`Self::new`].
    pub fn market(
        client_order_id: ClientOrderId,
        instrument: Instrument,
        side: Side,
        qty: Qty,
        authority: Authority,
        trace_id: TraceId,
    ) -> Result<Self, IntentError> {
        Self::new(
            client_order_id,
            instrument,
            side,
            qty,
            OrderKind::Market,
            None,
            None,
            authority,
            trace_id,
            None,
        )
    }

    /// A resting limit order.
    ///
    /// # Errors
    /// [`IntentError`] under the same rules as [`Self::new`].
    pub fn limit(
        client_order_id: ClientOrderId,
        instrument: Instrument,
        side: Side,
        qty: Qty,
        price: Price,
        authority: Authority,
        trace_id: TraceId,
    ) -> Result<Self, IntentError> {
        Self::new(
            client_order_id,
            instrument,
            side,
            qty,
            OrderKind::Limit,
            Some(price),
            None,
            authority,
            trace_id,
            None,
        )
    }

    /// A venue-native stop that survives this process dying.
    ///
    /// # Errors
    /// [`IntentError`] under the same rules as [`Self::new`].
    pub fn stop_market(
        client_order_id: ClientOrderId,
        instrument: Instrument,
        side: Side,
        qty: Qty,
        trigger: Price,
        trace_id: TraceId,
    ) -> Result<Self, IntentError> {
        Self::new(
            client_order_id,
            instrument,
            side,
            qty,
            OrderKind::StopMarket,
            None,
            Some(trigger),
            // A resting stop is a protective exit by definition. Nothing opens
            // exposure with one, and letting a caller claim otherwise would let
            // an entry guard be bypassed by choosing an order kind.
            Authority::ProtectiveExit,
            trace_id,
            None,
        )
    }

    /// Whether this intent may create new exposure.
    #[must_use]
    pub const fn opens_exposure(&self) -> bool {
        self.authority.opens_exposure()
    }

    /// The signed position delta this intent would produce if filled entirely.
    #[must_use]
    pub fn signed_qty(&self) -> Qty {
        Qty::from_raw(self.qty.raw().saturating_mul(self.side.sign()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn coid(s: &str) -> ClientOrderId {
        ClientOrderId::new(s).unwrap()
    }

    fn btc() -> Instrument {
        Instrument::new("BTCUSD").unwrap()
    }

    #[test]
    fn a_market_entry_validates() {
        let i = EconomicOrderIntent::market(
            coid("UI-1"),
            btc(),
            Side::Buy,
            Qty::whole(3),
            Authority::Entry,
            TraceId::from_u128(7),
        )
        .unwrap();
        assert!(i.opens_exposure());
        assert_eq!(i.signed_qty(), Qty::whole(3));
        assert_eq!(i.limit_price, None);
    }

    #[test]
    fn quantity_must_be_positive_because_direction_lives_in_side() {
        for q in [Qty::ZERO, Qty::whole(-1)] {
            assert_eq!(
                EconomicOrderIntent::market(
                    coid("UI-1"),
                    btc(),
                    Side::Sell,
                    q,
                    Authority::Entry,
                    TraceId::NONE,
                ),
                Err(IntentError::NonPositiveQty)
            );
        }
    }

    #[test]
    fn an_empty_idempotency_key_is_refused() {
        // Without it there is nothing for a retry to collapse onto, and
        // duplicate exposure stops being structurally impossible.
        assert_eq!(
            EconomicOrderIntent::market(
                ClientOrderId::empty(),
                btc(),
                Side::Buy,
                Qty::whole(1),
                Authority::Entry,
                TraceId::NONE,
            ),
            Err(IntentError::EmptyIdempotencyKey)
        );
    }

    #[test]
    fn stop_limit_is_refused_rather_than_approximated() {
        assert_eq!(
            EconomicOrderIntent::new(
                coid("UI-1"),
                btc(),
                Side::Sell,
                Qty::whole(1),
                OrderKind::Limit,
                Some(Price::whole(100)),
                Some(Price::whole(99)),
                Authority::ProtectiveExit,
                TraceId::NONE,
                None,
            ),
            Err(IntentError::StopLimitUnsupported)
        );
    }

    #[test]
    fn a_kind_without_the_price_it_needs_is_refused() {
        assert_eq!(
            EconomicOrderIntent::new(
                coid("UI-1"),
                btc(),
                Side::Buy,
                Qty::whole(1),
                OrderKind::Limit,
                None,
                None,
                Authority::Entry,
                TraceId::NONE,
                None,
            ),
            Err(IntentError::MissingPrice {
                kind: OrderKind::Limit
            })
        );
        assert_eq!(
            EconomicOrderIntent::new(
                coid("UI-1"),
                btc(),
                Side::Sell,
                Qty::whole(1),
                OrderKind::StopMarket,
                None,
                None,
                Authority::ProtectiveExit,
                TraceId::NONE,
                None,
            ),
            Err(IntentError::MissingPrice {
                kind: OrderKind::StopMarket
            })
        );
    }

    #[test]
    fn prices_must_be_positive() {
        for bad in [Price::ZERO, Price::whole(-1)] {
            assert_eq!(
                EconomicOrderIntent::limit(
                    coid("UI-1"),
                    btc(),
                    Side::Buy,
                    Qty::whole(1),
                    bad,
                    Authority::Entry,
                    TraceId::NONE,
                ),
                Err(IntentError::NonPositivePrice)
            );
        }
    }

    #[test]
    fn a_resting_stop_is_always_a_protective_exit() {
        // Not a default a caller may override: choosing an order kind must not
        // be a way to route around an entry guard.
        let i = EconomicOrderIntent::stop_market(
            coid("UI-1"),
            btc(),
            Side::Sell,
            Qty::whole(3),
            Price::whole(95_000),
            TraceId::NONE,
        )
        .unwrap();
        assert_eq!(i.authority, Authority::ProtectiveExit);
        assert!(!i.opens_exposure());
    }

    #[test]
    fn a_sell_intent_is_a_negative_delta() {
        let i = EconomicOrderIntent::market(
            coid("UI-1"),
            btc(),
            Side::Sell,
            Qty::whole(3),
            Authority::ProtectiveExit,
            TraceId::NONE,
        )
        .unwrap();
        assert_eq!(i.signed_qty(), Qty::whole(-3));
    }
}
